version: '2'
services:
        app:
                image: yash1600/spring-pet:v4
                container_name: app
                ports:
                        - 8080:8080
                environment:
                        - SPRING_DATASOURCE_URL=jdbc:postgresql://db/compose-postgres
                        - SPRING_DATASOURCE_USERNAME=compose-postgres
                        - SPRING_DATASOURCE_PASSWORD=compose-postgres
                        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        db:
                image: 'postgres:13.1-alpine'
                container_name: db
                environment:
                        - POSTGRES_USER=compose-postgres
                        - POSTGRES_PASSWORD=compose-postgres

                volumes:
                        - user_data:/var/lib/postgresql

 
        prometheus:

                image: prom/prometheus:v2.38.0

                network_mode: host

                container_name: prometheus-container

                volumes:

                        - ./prometheus.yml:/etc/prometheus/prometheus.yml

                command:

                        - '--config.file=/etc/prometheus/prometheus.yml'

                ports:

                        - "9090:9090"
        grafana:
                image: grafana/grafana-oss:9.1.4
                user: "$UID:$GID"
                network_mode: host
                container_name: grafana-container
                depends_on:
                        - prometheus
                ports:
                        - "3000:3000"
                volumes:
                        - ./grafana/:/var/lib/grafana
                environment:
                        - GF_SECURITY_ADMIN_PASSWORD=admin
                        - GF_SERVER_DOMAIN=localhost
volumes:
        user_data:
                driver: local