scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'My Spring Boot Application'
  - job_name: 'prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['127.0.0.1:9090']